project_id = "qwtybhvdbbkbcelisuek"

[functions.send-invitation-email]
verify_jwt = false

[functions.send-enhanced-email]
verify_jwt = false

[functions.create-paystack-checkout]
verify_jwt = true

[functions.verify-paystack-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.test-deploy]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false

[functions.billing-notifications]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false