# DigitalOcean App Platform specification
name: vibenet-pos-system
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  run_command: npm run preview -- --host 0.0.0.0 --port 8080
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  build_command: npm run build
  engines:
    node: "18"
  envs:
  - key: VITE_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  routes:
  - path: /
    preserve_path_prefix: false