# DigitalOcean App Platform specification
name: vibenet-pos-system
services:
- name: web
  source_dir: /
  github:
    repo: vibenet-pos-system
    branch: main
    deploy_on_push: false
  run_command: npx serve dist -s -l 8080
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8080
  build_command: npm ci --prefer-offline --no-audit && npm run build
  engines:
    node: "18.x"
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_SUPABASE_URL
    value: https://qwtybhvdbbkbcelisuek.supabase.co
  - key: VITE_SUPABASE_ANON_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3dHliaHZkYmJrYmNlbGlzdWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTE4MjYsImV4cCI6MjA2NzkyNzgyNn0.unXOuVkZ5zh4zizLe3wquHiDOBaPxKvbRduVUt5gcIE
  routes:
  - path: /
    preserve_path_prefix: false