name: Fast Deploy (No Tests)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - '*.json'
      - '*.ts'
      - '*.js'
    branches: [main]

jobs:
  fast-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies (production only)
      run: npm ci --production=false --prefer-offline --no-audit --ignore-scripts
      
    - name: Build optimized
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        NODE_ENV: production
        
    - name: Deploy to DigitalOcean
      uses: digitalocean/app_action@v1
      with:
        app_name: vibenet-pos-system
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}